#!/bin/bash

# A post-install hook script for the dotcould infrastructure.  This hook should
# do a few things:
#
#   * Load the history of legislative files from ScraperWiki
#   * Load the history of meetings and agendas from ScraperWiki
#   * Build the search indexes
#   * Set up daily cron jobs

# Link to the static files folder.
ln -s councilmatic/static/

# Do the management commands.
cd councilmatic
python manage.py syncdb --noinput
python manage.py migrate --noinput
python manage.py collectstatic --noinput

# Get ready for the search index.
mkdir ~/whoosh_index
#python manage.py rebuild_index --noinput

# Get ready for logs
mkdir ~/logs

# These are submodules of the project, but dotcloud doesn't handle submodules,
# so just clone the projects in their appropriate place.
cd static
git clone https://github.com/pilu/web-app-theme.git
git clone https://github.com/MBO/attrtastic.git
git clone https://github.com/justinfrench/formtastic.git

# Schedule the cron jobs
cd ../../
crontab - <<EOF
MAILTO=""
$[$RANDOM%60] $[$RANDOM%24] * * * "/home/dotcloud/current/crons/daily_jobs"
EOF
