#!/bin/bash

# A post-install hook script for the dotcould infrastructure.  This hook should
# do a few things:
#
#   * Load the history of legislative files from ScraperWiki
#   * Load the history of meetings and agendas from ScraperWiki
#   * Build the search indexes
#   * Set up daily cron jobs

python councilmatic/manage.py syncdb --noinput
python councilmatic/manage.py migrate --noinput

python councilmatic/manage.py collectstatic --noinput

