#!/bin/bash

mkdir councilmatic/whoosh_index
python councilmatic/manage.py loadlegfiles
python councilmatic/manage.py rebuild_index --noinput

crontab - <<EOF
MAILTO=""
$[$RANDOM%60] $[$RANDOM%24] * * * "~/current/crons/daily_jobs ~/current"
EOF

