#!/bin/bash

# Set COUNCILMATIC_DIR to the absolute path of the Django project's root folder.
COUNCILMATIC_DIR=/home/dotcloud/current/councilmatic
COUNCILMATIC_ENV=/home/dotcloud/env/bin/activate

source "$COUNCILMATIC_ENV"
cd "$COUNCILMATIC_DIR"
python manage.py updatelegfiles
python manage.py update_index --age=168
python manage.py cleanfeeds
python manage.py updatefeeds
python manage.py sendfeedupdates

# Update previous legfiles.  This means that updates to older content will
# always be a little behind, but it's better than nothing.
python manage.py updatelegfiles --update
