#!/bin/bash

# Set COUNCILMATIC_DIR to the absolute path of the Django project's root folder.
COUNCILMATIC_DIR=/var/www/html/councilmatic/councilmatic

echo "testing cron"

cd "$COUNCILMATIC_DIR"
python manage.py updatelegfiles

python manage.py update_index
python manage.py cleanfeeds
python manage.py updatefeeds
python manage.py sendfeedupdates

