-- updates photo paths for Chicago Aldermen

UPDATE phillyleg_councilmember set headshot='chicago/aldermen/47-ameya-pawar.jpg' where name='Ameya Pawar';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/9-anthony-beale.jpg' where name='Anthony Beale';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/30-ariel-reboyras.jpg' where name='Ariel Reboyras';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/2-robert-fioretti.jpg' where name='Bob Fioretti';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/42-brendan-reilly.jpg' where name='Brendan Reilly';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/34-carrie-austin.jpg' where name='Carrie M. Austin';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/25-daniel-solis.jpg' where name='Daniel Solis';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/29-deborah-graham.jpg' where name='Deborah L. Graham';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/50-debra-silverstein.jpg' where name='Debra L. Silverstein';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/14-edward-burke.jpg' where name='Edward M. Burke';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/37-emma-mitts.jpg' where name='Emma Mitts';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/12-george-cardenas.jpg' where name='George A. Cardenas';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/48-harry-osterman.jpg' where name='Harry Osterman';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/21-howard-brookins.jpg' where name='Howard  Jr. Brookins';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/11-james-balcer.jpg' where name='James Balcer';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/46-james-cappleman.jpg' where name='James Cappleman';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/28-jason-ervin.jpg' where name='Jason C. Ervin';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/16-joann-thompson.jpg' where name='Joann Thompson';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/45-john-arena.jpg' where name='John Arena';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/10-john-pope.jpg' where name='John Pope';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/49-joe-moore.jpg' where name='Joseph Moore';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/17-latasha-thomas.jpg' where name='Latasha R. Thomas';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/5-leslie-hairston.jpg' where name='Leslie A. Hairston';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/18-lona-lane.jpg' where name='Lona Lane';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/39-margaret-laurino.jpg' where name='Margaret Laurino';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/13-marty-quinn.jpg' where name='Marty Quinn';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/41-mary-oconnor.jpg' where name='Mary O''Connor';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/19-matthew-oshea.jpg' where name='Matthew J. O''Shea';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/24-michael-chandler.jpg' where name='Michael D. Chandler';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/23-michael-zalewski.jpg' where name='Michael R. Zalewski';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/43-michele-smith.jpg' where name='Michele Smith';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/8-michelle-harris.jpg' where name='Michelle A. Harris';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/36-nicholas-sposato.jpg' where name='Nicholas Sposato';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/3-pat-dowell.jpg' where name='Pat Dowell';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/40-patrick-oconnor.jpg' where name='Patrick O''Connor';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/1-joe-moreno.jpg' where name='Proco Joe Moreno';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/31-ray-suarez.jpg' where name='Regner Ray Suarez';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/35-rey-colon.jpg' where name='Rey Colón';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/22-ricardo-munoz.jpg' where name='Ricardo Munoz';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/33-richard-mell.jpg' where name='Richard F. Mell';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/26-roberto-maldonado.jpg' where name='Roberto Maldonado';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/6-roderick-sawyer.jpg' where name='Roderick T. Sawyer';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/7-jackson-sandi.jpg' where name='Sandi Jackson';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/32-scott-waguespack.jpg' where name='Scott Waguespack';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/44-thomas-tunney.jpg' where name='Thomas Tunney';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/38-timothy-cullerton.jpg' where name='Timothy M. Cullerton';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/15-toni-foulkes.jpg' where name='Toni Foulkes';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/27-alderman-burnett.jpg' where name='Walter  Jr. Burnett';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/4-william-burns.jpg' where name='William D. Burns';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/20-willie-cochran.jpg' where name='Willie Cochran';

UPDATE phillyleg_councilmember set headshot='chicago/aldermen/rahm-emanuel.jpg' where name='Rahm Emanuel';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/richard-m-daley.jpg' where name='Richard M. Daley';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/susana_mendoza.jpg' where name='Susana A. Mendoza';

-- no headshot
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Bernard Stone';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Brian Doherty'
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Ed Smith';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Eugene Schulter';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Frank Olivo';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Freddrenna Lyle';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Helen Shiller';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='John Rice';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Mary Ann Smith';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Miguel Del Valle';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Natashia Holmes';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Patrick Levar';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Sharon Dixon';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Shirley Newsome';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Thomas Allen';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Toni Preckwinkle';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Vi Daley';
-- UPDATE phillyleg_councilmember set headshot='chicago/aldermen/' where name='Virginia Rugai';