-- updates photo paths for Chicago Aldermen

UPDATE phillyleg_councilmember set headshot='chicago/aldermen/47-ameya-pawar.jpg', title='47th Ward Alderman' where name='Ameya Pawar';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/9-anthony-beale.jpg', title='9th Ward Alderman' where name='Anthony Beale';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/30-ariel-reboyras.jpg', title='30th Ward Alderman' where name='Ariel Reboyras';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/2-robert-fioretti.jpg', title='2nd Ward Alderman' where name='Bob Fioretti';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/42-brendan-reilly.jpg', title='42nd Ward Alderman' where name='Brendan Reilly';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/34-carrie-austin.jpg', title='34th Ward Alderman' where name='Carrie M. Austin';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/25-daniel-solis.jpg', title='15th Ward Alderman'  where name='Daniel Solis';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/29-deborah-graham.jpg', title='19th Ward Alderman'  where name='Deborah L. Graham';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/50-debra-silverstein.jpg', title='50th Ward Alderman'  where name='Debra L. Silverstein';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/14-edward-burke.jpg', title='14th Ward Alderman'  where name='Edward M. Burke';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/37-emma-mitts.jpg', title='37th Ward Alderman'  where name='Emma Mitts';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/12-george-cardenas.jpg', title='12th Ward Alderman'  where name='George A. Cardenas';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/48-harry-osterman.jpg', title='48th Ward Alderman'  where name='Harry Osterman';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/21-howard-brookins.jpg', title='31st Ward Alderman'  where name='Howard  Jr. Brookins';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/11-james-balcer.jpg', title='11th Ward Alderman'  where name='James Balcer';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/46-james-cappleman.jpg', title='46th Ward Alderman'  where name='James Cappleman';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/28-jason-ervin.jpg', title='28th Ward Alderman'  where name='Jason C. Ervin';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/16-joann-thompson.jpg', title='16th Ward Alderman'  where name='Joann Thompson';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/45-john-arena.jpg', title='45th Ward Alderman'  where name='John Arena';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/10-john-pope.jpg', title='10th Ward Alderman'  where name='John Pope';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/49-joe-moore.jpg', title='49th Ward Alderman'  where name='Joseph Moore';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/17-latasha-thomas.jpg', title='17th Ward Alderman'  where name='Latasha R. Thomas';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/5-leslie-hairston.jpg', title='5th Ward Alderman'  where name='Leslie A. Hairston';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/18-lona-lane.jpg', title='18th Ward Alderman'  where name='Lona Lane';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/39-margaret-laurino.jpg', title='39th Ward Alderman'  where name='Margaret Laurino';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/13-marty-quinn.jpg', title='13th Ward Alderman'  where name='Marty Quinn';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/41-mary-oconnor.jpg', title='41st Ward Alderman'  where name='Mary O''Connor';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/19-matthew-oshea.jpg', title='19th Ward Alderman'  where name='Matthew J. O''Shea';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/24-michael-chandler.jpg', title='24th Ward Alderman'  where name='Michael D. Chandler';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/23-michael-zalewski.jpg', title='23rd Ward Alderman'  where name='Michael R. Zalewski';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/43-michele-smith.jpg', title='43rd Ward Alderman'  where name='Michele Smith';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/8-michelle-harris.jpg', title='8th Ward Alderman'  where name='Michelle A. Harris';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/36-nicholas-sposato.jpg', title='36th Ward Alderman'  where name='Nicholas Sposato';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/3-pat-dowell.jpg', title='3rd Ward Alderman'  where name='Pat Dowell';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/40-patrick-oconnor.jpg', title='40th Ward Alderman'  where name='Patrick O''Connor';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/1-joe-moreno.jpg', title='1st Ward Alderman'  where name='Proco Joe Moreno';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/31-ray-suarez.jpg', title='31st Ward Alderman'  where name='Regner Ray Suarez';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/35-rey-colon.jpg', title='35th Ward Alderman'  where name='Rey Colón';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/22-ricardo-munoz.jpg', title='22nd Ward Alderman'  where name='Ricardo Munoz';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/33-richard-mell.jpg', title='33rd Ward Alderman'  where name='Richard F. Mell';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/26-roberto-maldonado.jpg', title='26th Ward Alderman'  where name='Roberto Maldonado';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/6-roderick-sawyer.jpg', title='6th Ward Alderman'  where name='Roderick T. Sawyer';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/7-jackson-sandi.jpg', title='Former 7th Ward Alderman'  where name='Sandi Jackson';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/32-scott-waguespack.jpg', title='32nd Ward Alderman'  where name='Scott Waguespack';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/44-thomas-tunney.jpg', title='44th Ward Alderman'  where name='Thomas Tunney';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/38-timothy-cullerton.jpg', title='38th Ward Alderman'  where name='Timothy M. Cullerton';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/15-toni-foulkes.jpg', title='15th Ward Alderman'  where name='Toni Foulkes';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/27-alderman-burnett.jpg', title='27th Ward Alderman'  where name='Walter  Jr. Burnett';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/4-william-burns.jpg', title='4th Ward Alderman'  where name='William D. Burns';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/20-willie-cochran.jpg', title='20th Ward Alderman'  where name='Willie Cochran';

UPDATE phillyleg_councilmember set headshot='chicago/aldermen/rahm-emanuel.jpg', title='Mayor of Chicago' where name='Rahm Emanuel';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/richard-m-daley.jpg', title='Former Mayor of Chicago' where name='Richard M. Daley';
UPDATE phillyleg_councilmember set headshot='chicago/aldermen/susana_mendoza.jpg', title='City Clerk of Chicago' where name='Susana A. Mendoza';

-- no headshot
UPDATE phillyleg_councilmember set title='Former 50th Ward Alderman' where name='Bernard Stone';
UPDATE phillyleg_councilmember set title='Former 41st Ward Alderman' where name='Brian Doherty';
UPDATE phillyleg_councilmember set title='Former 28th Ward Alderman' where name='Ed Smith';
UPDATE phillyleg_councilmember set title='Former 47th Ward Alderman' where name='Eugene Schulter';
UPDATE phillyleg_councilmember set title='Former 13th Ward Alderman' where name='Frank Olivo';
UPDATE phillyleg_councilmember set title='Former 6th Ward Alderman' where name='Freddrenna Lyle';
UPDATE phillyleg_councilmember set title='Former 46th Ward Alderman' where name='Helen Shiller';
UPDATE phillyleg_councilmember set title='Former 36th Ward Alderman' where name='John Rice';
UPDATE phillyleg_councilmember set title='Former 48th Ward Alderman' where name='Mary Ann Smith';
UPDATE phillyleg_councilmember set title='Former City Clerk of Chicago' where name='Miguel Del Valle';
UPDATE phillyleg_councilmember set title='7th Ward Alderman' where name='Natashia Holmes';
UPDATE phillyleg_councilmember set title='Former 45th Ward Alderman' where name='Patrick Levar';
UPDATE phillyleg_councilmember set title='Former 24th Ward Alderman' where name='Sharon Dixon';
UPDATE phillyleg_councilmember set title='Former 4th Ward Alderman' where name='Shirley Newsome';
UPDATE phillyleg_councilmember set title='Former 38th Ward Alderman' where name='Thomas Allen';
UPDATE phillyleg_councilmember set title='Former 4th Ward Alderman' where name='Toni Preckwinkle';
UPDATE phillyleg_councilmember set title='Former 43th Ward Alderman' where name='Vi Daley';
UPDATE phillyleg_councilmember set title='Former 19th Ward Alderman' where name='Virginia Rugai';